---
title: "Group 22 CA Pollution Burden"
author: "Michelle Geldin and Alessandra Puig-Santana"
date: "11/14/2021"
output: html_document
---

```{r setup, include=FALSE, warning = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(tidyverse)
library(janitor)
library(here)
library(gapminder)
```

```{r, warning = FALSE, message = FALSE}
ces <- read_csv(here("data", "ces3demographics.csv")) %>%
  clean_names
```

```{r gg-oz-gapminder, fig.cap = "Figure 1: CalEnviroScreen Pollution Burden Score Compared Against the Percentage of White Individuals"}
# Creating a basic ggplot demonstrating the white population vs. CalEnviroScreen pollution burden score

ggplot(data = ces, aes(x = white_percent,
                       y = ces_3_0_score)) +
  geom_hex() +
  labs(x = "Percent White", y = "CalEnviroScreen Pollution Burden Score") +
  scale_fill_gradient(low = "peachpuff", high = "red4") +
  theme_minimal()
```
Data Citation:

https://oehha.ca.gov/calenviroscreen/report/calenviroscreen-30
https://www.census.gov/prod/cen2010/cph-2-6.pdf
